CREATE INDEX `JOB_ARG_ID` on `JOB_ARG` (`ID`);
CREATE INDEX `DICTIONARY_TEXT` ON `DICTIONARY` (`TEXT`);
CREATE INDEX `DICTIONARY_LANGUAGE` ON `DICTIONARY` (`LANGUAGE`);
CREATE INDEX `ANNOTATION_MP_IDX` on `ANNOTATION` (`MEDIA_PACKAGE_ID`);
CREATE INDEX `USER_ACTION_USER_IDX` on `USER_ACTION` (`USER_ID`);
CREATE INDEX `USER_ACTION_MP_IDX` on `USER_ACTION` (`MEDIA_PACKAGE_ID`);
