# Configuration for the smtp service

# The transport protocol to use
# Accepted values are smtp or smtps
# Defaults to smtp
#mail.transport.protocol=

# Hostname or ip of the SMTP server.
mail.smtp.host=localhost
mail.smtps.host=localhost

# Which port to use when talking to the SMTP server.
# The default ports are 25 for plain SMTP, 465 for
# SMTPs and 587 for authenticated SMTP + TLS
#mail.smtp.port=25
#mail.smtps.port=465

# Whether to enable SMTP over SSL
#mail.smpt.ssl.enable=true

# Whether to enable tls over smt. Possible values are
# 'true or false'.
#mail.smtp.starttls.enable=true

# Username to be used when authenticating with the SMPT
# server in conjunction with mail.password.
# Leave empty if no authentication is required.
#mail.user=

# Password to be used when authenticating with the SMPT
# server in conjunction with mail.user.
# Leave empty if no authentication is required.
#mail.password=

# The sender mail address. Some SMTP services require
# this to be a valid e-mail address from their mail domain.
mail.from=

# Property that switches debug output on or off. Set to
# 'true' to enable debug output, 'false' otherwise.
#mail.debug=

# Property that triggers sending a test message on service
# startup. Set to 'true' to enable testing, 'false' otherwise.
#mail.test=